#!/usr/bin/env php
<?php

use Mach3queue\Command;
use Mach3queue\Queue\Queue;
use Mach3queue\Worker\Worker;
use Mach3queue\Worker\WorkerActions;
use Mach3queue\Worker\WorkerOptions;

$file = __DIR__ . '/../../autoload.php';

if (!(file_exists($file) && include $file)) {
    fwrite(STDERR, 'Install dependencies using Composer.'.PHP_EOL);
    exit(1);
}

$config = require __DIR__.'/../../../config.php';

$command = new Command($argv);
$queue = new Queue;
$queue->setConnection([
    'driver' => $config['db_driver'] ?? 'mysql',
    'host' => $config['db_host'],
    'database' => $config['db_name'],
    'username' => $config['db_user'],
    'password' => $config['db_pass'],
]);

$worker = new Worker(
    queue: $queue->on($command->getQueue()),
    timeout: $command->getTimeout(),
    actions: new WorkerActions,
    options: new WorkerOptions(
        stop_when_empty: $command->getStopWhenEmpty(),
    ),
);

$worker->run();