#!/usr/bin/env php
<?php

use Mach3queue\Console\Console;

/*
|--------------------------------------------------------------------------
| Config file
|--------------------------------------------------------------------------
|
| Load the config file that is needed for the queue to work.
|
*/

$queue_config = require  __DIR__.'/../../../queue.php';

/*
|--------------------------------------------------------------------------
| Bootstrap
|--------------------------------------------------------------------------
|
| Bootstrap the application, this is needed to load the environment.
|
*/

$bootstrap = $queue_config['bootstrap'];

if (!(file_exists($bootstrap) && include $bootstrap)) {
    fwrite(STDERR, 'Failed to load bootstrap.'.PHP_EOL);
    exit(1);
}

/*
|--------------------------------------------------------------------------
| Console
|--------------------------------------------------------------------------
|
| The console that runs the whole application.
|
*/

(new Console($queue_config))->handle($argv);
