#!/usr/bin/env php
<?php

use Mach3queue\Console\Console;

/*
|--------------------------------------------------------------------------
| Copy the config file over
|--------------------------------------------------------------------------
|
| If there is no config file, copy it over from the package.
|
*/

$source = __DIR__.'/config/queue.php';
$destination = __DIR__.'/../../../queue.php';

if (!file_exists($destination)) {
    copy($source, $destination);
}

/*
|--------------------------------------------------------------------------
| Config file
|--------------------------------------------------------------------------
|
| Load the config file that is needed for the queue to work.
|
*/

$config = require  __DIR__.'/../../../queue.php';

/*
|--------------------------------------------------------------------------
| Bootstrap
|--------------------------------------------------------------------------
|
| Bootstrap the application, this is needed to load the environment.
|
*/

$bootstrap = $config['bootstrap'];

if (!(file_exists($bootstrap) && include $bootstrap)) {
    fwrite(STDERR, 'Failed to load bootstrap.'.PHP_EOL);
    exit(1);
}

/*
|--------------------------------------------------------------------------
| Console
|--------------------------------------------------------------------------
|
| The console that runs the whole application.
|
*/

(new Console($config))->handle($argv);
